window.Theme?.initTheme();
const state = JSON.parse(sessionStorage.getItem('msykSchoolExercise') || 'null');
if (!state?.questions?.length) location.replace('./index.html');
let current = 0; let submitting = false; const results = new Map();
const elapsed = () => Math.max(0, Math.floor((Date.now() - Number(state.startedAt || Date.now())) / 1000));
function tick() { const n = elapsed(); document.getElementById('timer').textContent = [Math.floor(n / 3600), Math.floor(n % 3600 / 60), n % 60].map((v) => String(v).padStart(2, '0')).join(':'); }
function receive(detail) { const question = state.questions.find((item) => item.questionId === String(detail.questionId)); if (!question) return; const correct = Number(detail.isCorrect) !== 0; results.set(question.questionId, { ...question, answer: String(detail.answer || ''), isError: correct ? 0 : 1 }); renderBar(); if (correct && current < state.questions.length - 1) setTimeout(() => show(current + 1), 250); }
window.addEventListener('msyk-school-answer', (event) => receive(event.detail || {}));
function installDesktopCallback(viewer) { if (typeof viewer.executeJavaScript !== 'function') return; viewer.executeJavaScript(`window.jsCallback={getAnswer:(answer,questionId,isCorrect)=>console.log('__MSYK_SCHOOL_ANSWER__'+JSON.stringify({answer,questionId,isCorrect})),isOpenTime:()=>{}}`, true).catch(() => {}); }
function wireViewer(viewer) { if (viewer.__schoolExerciseWired) return; viewer.__schoolExerciseWired = true; viewer.addEventListener?.('dom-ready', () => installDesktopCallback(viewer)); viewer.addEventListener?.('console-message', (event) => { const marker = '__MSYK_SCHOOL_ANSWER__'; const message = String(event.message || ''); if (message.startsWith(marker)) { try { receive(JSON.parse(message.slice(marker.length))); } catch {} } }); }
function renderBar() { document.querySelectorAll('#answerBar button').forEach((button, index) => { const id = state.questions[index].questionId; button.classList.toggle('active', index === current); button.style.boxShadow = results.has(id) ? `inset 0 -3px ${results.get(id).isError ? 'var(--danger)' : '#22c55e'}` : ''; }); }
async function show(index) { current = index; document.getElementById('progress').textContent = `第 ${index + 1} / ${state.questions.length} 题`; renderBar(); const response = await window.msykAPI.schoolExerciseQuestionUrl({ questionId: state.questions[index].questionId, gradeCode: state.gradeCode }); if (response?.code !== 200) throw new Error(response?.msg || '题目加载失败'); const viewer = document.getElementById('questionView'); wireViewer(viewer); viewer.src = response.data?.url || response.data?.data?.url || ''; }
state.questions.forEach((item, index) => { const button = document.createElement('button'); button.type = 'button'; button.textContent = index + 1; button.addEventListener('click', () => show(index).catch((error) => alert(error.message))); document.getElementById('answerBar').appendChild(button); });
async function save() { if (submitting || !confirm('保存本次练习记录并退出？')) return; submitting = true; try { const questionRef = [...results.values()].map(({ questionId, orderNum, tagId, isError }) => ({ questionId, orderNum, tagId, isError, dirId: state.dirId })); const correctNum = questionRef.filter((item) => item.isError === 0).length; const response = await window.msykAPI.schoolExerciseSaveResult({ doTime: elapsed(), questionRef, subjectCode: state.subjectCode, gradeCode: state.gradeCode, errorNum: questionRef.length - correctNum, correctNum, dirId: state.dirId }); if (response?.code !== 200 || !['', '10000', '200'].includes(String(response.data?.code ?? ''))) throw new Error(response?.msg || response.data?.message || '保存失败'); sessionStorage.removeItem('msykSchoolExercise'); alert(`已保存：答对 ${correctNum} 题，答错 ${questionRef.length - correctNum} 题`); location.replace('./index.html'); } catch (error) { alert(error.message); submitting = false; } }
document.getElementById('submitBtn').addEventListener('click', save); document.getElementById('closeBtn').addEventListener('click', save); setInterval(tick, 1000); tick(); show(0).catch((error) => alert(error.message));
